site_name: Money Eva Knowledge Hub
site_url: https://docs.moneyeva.com
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
  
  font:
    text: Roboto
  logo: https://moneyeva.com/android-chrome-192x192.png
  favicon: https://moneyeva.com/favicon.ico
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - search.highlight
    - search.suggest
copyright: >
  © 2024 Money Eva. This Knowledge Hub is open source and shaped by community contributions 
  on <a href="https://github.com/moneyeva/moneyeva-docs" target="_blank" rel="noopener">GitHub</a>.
  <br>
  <a href="#__consent">Change cookie settings</a>
extra:
  social:
    - icon: fontawesome/solid/rocket
      link: https://moneyeva.com
      name: 'Money Eva App'
    - icon: fontawesome/brands/github
      link: https://github.com/moneyeva/moneyeva-docs
      name: 'GitHub Repository'
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@learnmoneyeva
      name: 'YouTube @learnmoneyeva'
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@learnmoneyeva
      name: 'TikTok @learnmoneyeva'
  analytics:
    provider: google
    property: G-6X25VSVL2B
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Spot something to improve? Share your feedback directly on the <a href="https://github.com/moneyeva/moneyeva-docs" target="_blank" rel="noopener">GitHub repo</a> of this Knowledge Hub!
  consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
extra_css:
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - _stylesheets/extra.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - _javascripts/datatable.js
markdown_extensions:
  - admonition  # For callout boxes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - smarty  # For curly quotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - tax_rates_table

nav:
  - 'Overview': index.md
  - Intro:
    - 'What Is Money Eva?': intro/what-is-money-eva.md
    - Using Scenarios (No Login): intro/using-scenarios-no-login.md
    - Key Features: intro/key-features.md
    - Account Setup: intro/account-setup.md
  - Guides:
    - Exploring Scenarios: guides/exploring-scenarios.md
    - Creating Your Own: guides/creating-your-own.md
    - 'Saving & Sharing': guides/saving-and-sharing.md
    - Example Scenarios: guides/example-scenarios.md
  - 'Calculation Breakdown':
    - 'Cash Flow & Investment Basics': calculation-breakdown/cash-flow-and-investment-basics.md
    - 'Inputs': calculation-breakdown/inputs.md
    - 'Decisions/Expectations': calculation-breakdown/decisions-expectations.md
    - 'Calculations': calculation-breakdown/calculations.md
    - 'Math & Symbols Guide': calculation-breakdown/math-and-symbols-guide.md
  - Examples:
    - Common Use Cases: examples/common-use-cases.md
    - Calculating Tax Rates: examples/calculating-tax-rates.md
  - FAQ:
    - Common Questions: faq/common-questions.md
    - Troubleshooting: faq/troubleshooting.md
  - Updates:
    - New Features: updates/new-features.md
    - Release Notes: updates/release-notes.md
  - Community:
    - Give Feedback: community/give-feedback.md
    - Tips from Users: community/tips-from-users.md
